import { LOGOS, COMMON_LINKS } from './shared';
import type { TextContent } from '../../../types';

export const en: TextContent = {
    labels: {},
    iconImage: LOGOS.santex,
    coursesProviders: {
        Platzi: {
            about: 'Platzi is a Mexican online education platform focused on technology and digital skills, founded in 2011 by Freddy Vega. It offers courses and personalized learning paths in areas such as web development, artificial intelligence, marketing, and cybersecurity. \n\nTo obtain a certificate, students must pass an exam with a minimum score of 9 out of 10 (90%) and also submit a practical project following the guidelines from the videos, which must be approved. Currently, the diploma’s code cannot be validated, but profiles are public and display the completed courses.',
            url: COMMON_LINKS.platzi,
            logo: LOGOS.platzi,
        },
        'LinkedIn Learning': {
            about: 'LinkedIn Learning is an online learning platform with videos and courses taught by experts, providing individuals and organizations the opportunity to develop skills in areas such as business, technology, and creativity. \n\nTo obtain a certificate, students must complete all course modules and pass the included assessments, which consist of multiple-choice quizzes and, in some cases, practical exercises. Certificates are issued directly on the user’s LinkedIn profile, making acquired skills publicly validated.',
            url: COMMON_LINKS.linkedinLearning,
            logo: LOGOS.linkedin,
        },
        'Project Management Institute': {
            about: 'The Project Management Institute (PMI) is a nonprofit professional organization and the world’s leading authority in project management. It promotes the discipline, sets standards, provides certifications, and generates knowledge through research to empower professionals and organizations worldwide. \n\nTo obtain a certification such as PMP or CAPM, candidates must meet prerequisites in prior experience and academic training, as well as pass a rigorous multiple-choice exam that assesses both theoretical and practical project management knowledge. Certifications must be maintained through continuous education via Professional Development Units (PDUs).',
            logo: LOGOS.projectManagementInstitude,
        },
        'CPE Sponsors': {
            about: 'A CPE Sponsor is an organization or individual recognized by NASBA’s National Registry of CPE Sponsors that offers continuing professional education (CPE) programs that meet national standards. These programs help professionals, especially CPAs, maintain their skills and fulfill education requirements to retain certifications such as CPA or CMA. \n\nTo earn CPE hours, participants must attend training sessions, pass knowledge assessments, and in some cases submit practical assignments or case studies. The credits earned are recorded and may be audited by regulatory bodies.',
            logo: LOGOS.CPESponsors,
        },
        Busuu: {
            about: 'Busuu is an online language-learning platform similar to Duolingo, available as both a web and mobile application, offering interactive courses to learn and practice 14 languages. It combines self-study with a community system where users can correct each other’s exercises and receive feedback, as well as the option of live lessons with teachers and officially recognized certificates. \n\nTo obtain an official certificate, students must complete all levels of a language course and pass the final assessments. Certificates are issued in collaboration with partner educational organizations and reflect the level achieved according to the Common European Framework of Reference (CEFR).',
            logo: LOGOS.Busuu,
        },
        UTN: {
            about: 'The National Technological University (UTN) is a free, public university in Argentina dedicated to training engineers and technology professionals, with a network of regional faculties across the country. Founded in 1948 as the National Workers’ University, it focuses on public education, applied research for industrial and national development, and social inclusion, offering tuition-free programs with strong ties to the productive sector. \n\nTo complete courses and diploma programs, students must attend theoretical and practical classes, pass midterm and final exams, and in some cases present projects or integrative assignments. Certificates issued by UTN carry official recognition throughout Argentina.',
            logo: LOGOS.UTN,
        },
        Santex: {
            about: 'Santex is a technology company that organizes and supports XAcademy, a free and virtual training program designed to close the gap between the skills demanded in the IT sector and access to such training, fostering job placement in areas like programming and software testing. \n\nStudents participating in XAcademy must complete practical modules with guided projects and submit deliverables evaluated by company mentors. Once projects and assessments are approved, they receive a certificate endorsed by Santex, validating the acquired skills and serving as proof in job application processes.',
            logo: LOGOS.santex,
        },
    },
    greeting: 'Welcome to my portfolio!',
    about: "I am Jairo Leonardo Olivera Sawka, a fullstack developer based in LATAM with experience as a semi-senior developer at a multinational company based in London, England, United Kingdom. I have over 7 years of professional experience developing scalable Web Applications using Python, Django, Javascript (React.js, Node.js), and SQL databases. In my career I have worked from the full product development lifecycle, including backend architecture, API integration, interfaces, and containerization with Docker, to production support, bug fixes, and technical advice in cross-functional teams, which is even more important in a fast-paced environment. More recently I have been involved in AI development with hands-on projects, including a working LLM powered chatbot, and an object detection system using YOLOv8, using a structured version control system. I think that I can bring a combination of technical depth, communication skills, and ability to adapt to a given scenario on any project, and I strongly enjoy the opportunity to problem-solve in the real-world through clean coding practices, thoughtfully designed architecture, and a strong focus on learning.",
    skills: 'Technologies I use:',
    stack: {
        labels: ['Languages & Standards', 'Frontend', 'Backend', 'Databases', 'DevOps', 'Testing', 'Artificial inteligence', 'Tools', 'Soft skills', 'Languages'],
        languages: ['JavaScript', 'Typescript', 'Python', 'Java', 'SQL', 'C#', 'Bash', 'HTML', 'CSS'],
        frontend: ['React', 'Redux', 'Next', 'TailwindCSS', 'MaterialUI', 'Bootstrap', 'Responsive design', 'Accessibility', 'UX writing'],
        backend: ['NodeJs', 'Express', 'FastAPI', 'Django', 'GraphQL', 'RESTful API design', 'OAuth2', 'Token authentication', 'Access Control', 'Microservices', 'MVC', 'JSON', 'Postman'],
        databases: ['MySQL', 'PostgreSQL', 'MongoDB', 'SQLite'],
        devops: ['Docker', 'CI/CD', 'Git', 'Github', 'Azure', 'HTTPS'],
        testing: ['Jest', 'Cypress', 'Pytest', 'Unit testing', 'QA automation'],
        ai: ['OpenAI', 'Groq', 'LLM integration', 'YOLOv8', 'Pandas', 'Data visualization', 'Basic AI modeling'],
        tools: ["Wordpress", "Wix", "Duda", 'Odoo', 'Magento', 'Prestashop', 'Figma', 'Miro', 'Powerpoint', 'Google Sheets', 'Excel', 'Word', 'Airtable'],
        softskills: ['Teamwork', 'Troubleshooting', 'Critical thinking', 'Technical documentation', 'Project management', 'INTJ'],
        languagesSpoken: ['English', 'Italian', 'Japanese', 'Polish'],
    },
    workExperienceTitle: 'Work experience',
    workLabels: { from: 'From', to: 'to', position: 'Position/Role', company: 'Company', highlights: 'Responsibilities and achievements', technologies: 'Technologies' },
    workExperience: [
        { iconImage: LOGOS.PWC, from: 'Oct 2022', to: 'Dec 2024', jobtitle: 'Associate 2', company: 'Pricewaterhousecoopers', highlights: ['Delivered high-quality enhancements for a React-TypeScript web application for Bristol-Myers Squibb, ensuring project alignment and client satisfaction.', 'Led the migration of a SharePoint database to a scalable platform, improving efficiency and usability.', 'Maintained a robust Azure-based support platform for NBCUniversal, ensuring seamless operation and issue resolution.'], tecnologies: ['Trello', 'Miro', 'Figma', 'JavaScript', 'Python', '.NET', "C#", 'Sharepoint', 'React', 'Typescript', 'MySQL', 'JSON', 'Postman'] },
        { iconImage: LOGOS.Oliteam, from: 'Jan 2020', to: 'Oct 2022', jobtitle: 'Project Manager', company: 'OliTeam', highlights: ['Co-founded the organization, overseeing small-scale projects and mentoring new developers.', 'Introduced innovative programming pathways to accelerate skill development among junior team members.'], tecnologies: ['Java', 'Python', 'JavaScript', 'NodeJs', 'Express', 'React', 'Redux',"Wordpress", "Wix", "Duda", 'MongoDB', 'PostgreSQL', 'MySQL', 'PL/SQL', 'JSON', 'Postman'] },
        { iconImage: LOGOS.Halala, from: 'Jan 2020', to: 'Feb 2021', jobtitle: 'Frontend Developer', company: 'Halalá', highlights: ['Designed and developed a mobile-first e-commerce application connecting raw material producers with manufacturers.', 'Spearheaded the UI/UX design process, enhancing user engagement and navigation efficiency.'], tecnologies: ['JavaScript', 'React', 'Redux', 'PostgreSQL'] },
        { iconImage: LOGOS.Tecnicina, from: 'Oct 2013', to: 'Dec 2017', jobtitle: 'Database Manager', company: 'Tecnicina', highlights: ['Ensured the accuracy and functionality of a commerce database for medical equipment sales.', 'Resolved operational issues related to invoice printing and fiscal registration, enhancing workflow reliability'], tecnologies: ['Factusol', 'Magento', 'Prestashop', 'Odoo', 'Python', 'JavaScript', 'JSON', 'Postman'] },
    ],
    projectsTitle: 'Projects',
    projects: [
        {
            title: 'Nuntius',
            description: 'News CRUD application using React, TypeScript, Node.js, and PostgreSQL.',
            image: '/projects/nuntius/Nuntius_test.png',
            link: 'https://github.com/leosawka/nuntius',
        },
        {
            title: 'ToDo List',
            description: 'Simple task manager built with React and hosted with GitHub Pages.',
            image: '/projects/todolist/ToDoList.png',
            link: 'https://leosawka.github.io/ToDo/',
        },
        {
            title: 'Work in progress',
            description: 'I will complete this information as soon as possible.',
            image: '/projects/work in progress.png',
            link: 'https://github.com/leosawka',
        },
        {
            title: 'Work in progress #1',
            description: 'I will complete this information as soon as possible.',
            image: '/projects/work in progress.png',
            link: 'https://github.com/leosawka',
        },
        {
            title: 'Work in progress #2',
            description: 'I will complete this information as soon as possible.',
            image: '/projects/work in progress.png',
            link: 'https://github.com/leosawka',
        },
        {
            title: 'Work in progress #3',
            description: 'I will complete this information as soon as possible.',
            image: '/projects/work in progress.png',
            link: 'https://github.com/leosawka',
        },
        {
            title: 'Work in progress #4',
            description: 'I will complete this information as soon as possible.',
            image: '/projects/work in progress.png',
            link: 'https://github.com/leosawka',
        },
        {
            title: 'Work in progress #5',
            description: 'I will complete this information as soon as possible.',
            image: '/projects/work in progress.png',
            link: 'https://github.com/leosawka',
        },
    ],
    socialTitle: 'Social & Contact',
    social: [
        { label: 'Github', url: 'https://github.com/leosawka' },
        { label: 'Linkedin', url: 'https://www.linkedin.com/in/jairo-leonardo-olivera-sawka-623732b4/' },
        { label: 'Gmail', url: 'leonardo.sawka@gmail.com' },
        { label: 'Telegram', url: 'https://t.me/leonardosawka' },
        { label: 'Platzi', url: 'https://platzi.com/p/Sawka/' },
        { label: 'HackerRank', url: 'https://www.hackerrank.com/profile/Sawka' }
    ],
    coursesTitle: 'Courses',
    coursesLabels: { date: 'Date', ID: 'Certificate ID' },
    viewMore: 'Show More ▼',
    viewLess: 'Show Less ▲',
    courses: [
        {
            title: 'QA Automation',
            description: 'Intensive XAcademy program teaching manual testing and, upon completion, advancing to automated testing with Cypress and APIs in an online format.',
            date: 'August 7, 2025',
            certificateId: 'Does not have',
            logo: LOGOS.santex,
            provider: 'Santex',
        },
        {
            title: 'Introduction to machine learning',
            description: 'Introduces fundamental machine learning concepts such as supervised and unsupervised learning, model evaluation, and feature engineering.',
            date: 'April 11, 2025',
            certificateId: '5f6f09dO-4cdd-4668-9cec-554528bf29be',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'The secrets of interpersonal communication',
            description: 'Explores techniques to develop empathy, active listening, and conflict resolution skills essential for effective interpersonal communication.',
            date: 'April 07, 2025',
            certificateId: 'e7bd75a0c6116c65111c5860b00301f6c58fa2da9844fa1b70e80376cf2a2f2c',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Project Management Fundamentals: Small Projects',
            description: 'Covers core project management methodologies and the planning, execution, and closing phases tailored to small-scale projects.',
            date: 'March 29, 2025',
            certificateId: '889ed3a0a890f280e2a17d9b54acbe09ebee12afb5cc0b6f2da903f680421c2b',
            logo: LOGOS.projectManagementInstitude,
            provider: 'Project Management Institute',
        },
        {
            title: 'Python Data Structures: Stacks, Deques, and Queues',
            description: 'Explains how to implement and use stacks, deques, and queues in Python with practical examples and performance considerations.',
            date: 'March 19, 2025',
            certificateId: '20ae047f9fa7d58bab398e25fb8818281556f7454298221763269d38fd05467a',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Simplified project management',
            description: 'Offers a streamlined approach to project management techniques, focusing on efficiency and practical application for fast-paced environments.',
            date: 'March 19, 2025',
            certificateId: '096a973c00084b688a3c2ae5dee929be82afb2f52e15323b76bddea703ead7b6',
            logo: LOGOS.projectManagementInstitude,
            provider: 'Project Management Institute',
        },
        {
            title: 'Python Data Structures: Linked Lists',
            description: 'Teaches creation, traversal, and manipulation of linked lists in Python with emphasis on performance trade-offs.',
            date: 'March 18, 2025',
            certificateId: 'fc699f25238fc3b35c3bf63edf081c708e326c83dbad83a6fd0236c302251241',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Python Data Structures and Algorithms',
            description: 'Introduces essential data structures and algorithm design patterns in Python, including recursion and sorting techniques.',
            date: 'March 17, 2025',
            certificateId: '759900d11cb37f50e7b486988192a48bdd1af6f85187eb14bfc25a0d8110436c',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Advanced Python: Practical Database Examples',
            description: 'Demonstrates database interaction in Python using real-world examples involving SQL databases and ORMs.',
            date: 'March 07, 2025',
            certificateId: '83d11b8a007541ee3dc1b1e544e057565206595a78e6b02bbe8ca39328c838d7',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Advanced Python: Working with Databases',
            description: 'Explores advanced techniques for querying, handling transactions, and optimizing database operations in Python.',
            date: 'February 26, 2025',
            certificateId: '20b01b7dedb39a9a4472ada6eea77ae75589f7678b242247c367283934386297',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Teleworking and managing remote teams',
            description: 'Covers best practices, tools, and leadership strategies for effectively managing distributed and remote teams.',
            date: 'February 21, 2025',
            certificateId: 'a277f3adf2c306aa37e589a6e319827917d4738ae0c4a04aa0ca8824056601d6',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Advanced Python: Working With Data',
            description: 'Focuses on data manipulation and processing techniques in Python, including handling JSON, CSVs, and large datasets.',
            date: 'February 20, 2025',
            certificateId: '0562865fff9a168ddca24ca66d3928e1bdcba69ac02e4420988acbf7a737c93b',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Python Statistics Essential Training',
            description: 'Introduces basic statistical concepts and their implementation in Python, including descriptive statistics and data visualization.',
            date: 'February 17, 2025',
            certificateId: '4659c82fbc20cc5644c9bdb663b284562b4b808c57bafc22a7e724223bd9da34',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Python Statistics Essential Training (CPE)',
            description: 'Same as the essential training, with Continuing Professional Education (CPE) credits included.',
            date: 'February 17, 2025',
            certificateId: 'b497d69a8de2f88252ffad414fe63b10cde5ebd2b489eb0b1ff10ca3478bedf6',
            logo: LOGOS.CPESponsors,
            provider: 'CPE Sponsors',
        },
        {
            title: 'Foundational Math for Machine Learning',
            description: 'Covers core math foundations for machine learning, including linear algebra, calculus, and probability theory.',
            date: 'February 06, 2025',
            certificateId: 'e6c77c5aaeeafade3d656ed4ae790d8ec215f47d7df392e1d91d8fa41d9756a5',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Machine Learning Foundations: Statistics (CPE)',
            description: 'Presents statistical concepts essential for understanding machine learning, designed for CPE credits.',
            date: 'February 07, 2025',
            certificateId: '21014f9053fb006f8cb6a71bff3e5ef4f8b66227faaa005d99de63a24519d63c',
            logo: LOGOS.CPESponsors,
            provider: 'CPE Sponsors',
        },
        {
            title: 'Machine Learning Foundations: Statistics (LN)',
            description: 'Introduces ML-relevant statistics fundamentals, focusing on concepts like variance, correlation, and inference.',
            date: 'February 06, 2025',
            certificateId: '13c1115f65b43a09726f15c3d2739748e4bae3a0c372a842200b85344c499554',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Machine Learning Foundations: Probability',
            description: 'Covers probability theory essentials for ML, including Bayes theorem, distributions, and sampling methods.',
            date: 'February 05, 2025',
            certificateId: 'da1e89b23e30220ef96bca44c8b628bd99dbe7fb97338f5967acedd8bd9127ac',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Machine Learning Foundations: Calculus',
            description: 'Explores calculus topics such as derivatives and integrals, and their applications in optimization for ML.',
            date: 'February 03, 2025',
            certificateId: '5231f5fc974667ecb9f1f31155ea5f5b4924a93cdbb983ac1f51b418b6ae9167',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Machine Learning Foundations: Linear Algebra',
            description: 'Introduces vectors, matrices, and operations relevant to machine learning algorithms.',
            date: 'January 29, 2025',
            certificateId: '475599a829ce4c9544175528878e2df05ae33a4125a3bfb397248feee1c3f809',
            logo: LOGOS.linkedin,
            provider: 'LinkedIn Learning',
        },
        {
            title: 'Work management with Airtable',
            description: 'Teaches how to organize, track, and automate workflows in Airtable for efficient project and task management.',
            date: 'January 22, 2025',
            certificateId: '49e8a987-08ff-489e-a8cb-0388fa280ee4',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'Introduction to the terminal and command line',
            description: 'Practical introduction to the command line, covering navigation, file operations, and essential terminal tools.',
            date: 'October 21, 2024',
            certificateId: 'Oa320131-0b60-463d-aa74-eaa392c3db06',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'Upper Intermediate English B2',
            description: 'Course designed to consolidate listening, speaking, reading, and writing skills at the B2 level.',
            date: 'October 14, 2024',
            certificateId: '5196524b-3dfa-4a11-a53a-b3f93f55e954',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'Fundamentals of UX/UI interface design',
            description: 'Introduction to UX/UI principles, focusing on experience design and interface prototyping.',
            date: 'July 14, 2024',
            certificateId: '190fbdc9-d6df-4fc1-a880-f58803c9a85c',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'Guide to learning computer security',
            description: 'Introductory guide to key cybersecurity concepts and best practices for protecting systems.',
            date: 'June 06, 2024',
            certificateId: '90c6e780-1949-4dd2-aeec-af3e47f84890',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'React.Js',
            description: 'Covers the fundamentals of React.js, including components, state, and routing for modern frontend development.',
            date: 'March 13, 2024',
            certificateId: '5fe5fad7-1a9c-4f9b-976d-134c14906137',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'C# basics con .NET Core',
            description: 'Introduces fundamental concepts of programming in C# and development using .NET Core.',
            date: 'December 04, 2022',
            certificateId: 'e5445efO-2e90-482b-9575-7c7710e9c7f3',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: '.NET Fundamentals',
            description: 'Introduction to the .NET ecosystem, covering its architecture and main tools.',
            date: 'December 04, 2022',
            certificateId: '5b54f314-5002-4e68-b1aa-01e267a104c6',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'Professional Srum course',
            description: 'Professional Scrum training covering Scrum roles, events, and artifacts in agile environments.',
            date: 'November 14, 2022',
            certificateId: '3ec96a11-e093-4436-96fe-950cf07621eс',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'Object-Oriented Programming',
            description: 'Covers OOP principles such as classes, inheritance, and encapsulation.',
            date: 'November 07, 2022',
            certificateId: 'e1b18ed5-9256-4f5d-9d24-06670b6b3c2a',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'Git & Github',
            description: 'Introduction to Git and GitHub: version control, repositories, branches, and pull requests.',
            date: 'November 07, 2022',
            certificateId: '542a3d3d-a506-4200-9a90-c648d710c067',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'Basic programming',
            description: 'Beginner programming course covering logic, basic data structures, and fundamental syntax.',
            date: 'November 04, 2022',
            certificateId: 'e09b242f-4491-470a-85bd-8163ca3becaa',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'A1 level of Japanese',
            description: 'A1 level Japanese course focused on vocabulary, basic grammar, and everyday expressions.',
            date: 'September 21, 2022',
            certificateId: 'Does not have.',
            logo: LOGOS.Busuu,
            provider: 'Busuu',
        },
        {
            title: 'Introduction to C#',
            description: 'Introductory course on C# covering basic syntax, data types, and control structures.',
            date: 'February 04, 2022',
            certificateId: 'd1231e44-a9f0-4833-bd98-a3bc2e2f27ba',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'Fundamentals of Node.Js',
            description: 'Essential principles of Node.js for building server-side applications with JavaScript.',
            date: 'Octover 25, 2021',
            certificateId: '1775267f-9299-4a2a-9d03-6ab46a369f15',
            logo: LOGOS.platzi,
            provider: 'Platzi',
        },
        {
            title: 'Payroll Settlement',
            description: 'Provides theoretical and practical training to calculate wages, salaries, social security contributions, and deductions according to Argentine labor regulations.',
            date: 'December 10, 2018',
            certificateId: 'Does not have.',
            logo: LOGOS.UTN,
            provider: 'UTN',
        },
    ],
    contactTitle: 'Contact Me',
    contactForm: {
        name: 'Name',
        email: 'Email',
        message: 'Message',
        send: 'Send',
        success: 'Message sent!',
        error: 'Please complete all fields.',
        "invalidFormat": "Invalid email format.",
        "disposableEmail": "Disposable or blocked email addresses are not allowed.",
        "errorName": "Name is required.",
        "errorEmail": "Email is required.",
        "errorMessage": "Message is required."
    },
} as const;
