import { LOGOS, COMMON_LINKS } from './shared';
import type { TextContent } from '../../types';

export const es: TextContent = {
    labels: {},
  iconImage: LOGOS.santex,
  coursesProviders: {
    Platzi: {
      about: 'Platzi es una plataforma mexicana de educación en línea enfocada en tecnología y habilidades digitales, fundada en 2011 por Freddy Vega. Ofrece cursos y rutas de aprendizaje personalizadas en áreas como desarrollo web, inteligencia artificial, marketing y ciberseguridad. \n\nPara obtener un certificado, el estudiante debe aprobar un examen con una calificación mínima de 9 sobre 10 (90%) y además presentar un trabajo práctico siguiendo los lineamientos de los videos, el cual debe ser aprobado. Actualmente no se puede validar el código del diploma, pero los perfiles son públicos y muestran los cursos completados.',
      url: COMMON_LINKS.platzi,
      logo: LOGOS.platzi,
    },
    'LinkedIn Learning': {
      about: 'LinkedIn Learning es una plataforma de aprendizaje en línea con videos y cursos impartidos por expertos, que ofrece a las personas y organizaciones la oportunidad de desarrollar habilidades en áreas como negocios, tecnología y creatividad. \n\nPara obtener un certificado, los estudiantes deben completar todos los módulos del curso y aprobar las evaluaciones incluidas, que consisten en cuestionarios de opción múltiple y, en algunos casos, ejercicios prácticos. Los certificados se emiten directamente en el perfil de LinkedIn del usuario, permitiendo validar las competencias adquiridas de manera pública.',
      url: COMMON_LINKS.linkedinLearning,
      logo: LOGOS.linkedin,
    },
    'Project Management Institute': {
      about: 'El Project Management Institute (PMI) es una organización profesional sin fines de lucro y la principal autoridad mundial en gestión de proyectos, que promueve la disciplina, establece estándares, ofrece certificaciones y genera conocimiento a través de la investigación para empoderar a profesionales y organizaciones en todo el mundo. \n\nPara obtener una certificación como PMP o CAPM, los candidatos deben cumplir con requisitos de experiencia previa y formación académica, además de aprobar un examen riguroso de opción múltiple que evalúa conocimientos teóricos y prácticos en gestión de proyectos. Las certificaciones requieren mantenimiento continuo mediante créditos de desarrollo profesional (PDUs).',
      logo: LOGOS.projectManagementInstitude,
    },
    'CPE Sponsors': {
      about: 'Un CPE Sponsor (Patrocinador de CPE) es una organización o individuo reconocido por el Registro Nacional de Patrocinadores de CPE de la NASBA que ofrece programas de educación profesional continua (CPE) cumpliendo con estándares nacionales. Estos programas ayudan a los profesionales, especialmente a los contadores públicos, a mantener sus habilidades y cumplir con los requisitos de educación para conservar certificaciones como CPA o CMA. \n\nPara acreditar las horas de CPE, el participante debe asistir a las sesiones de formación, aprobar evaluaciones de conocimiento, y en algunos casos entregar trabajos prácticos o estudios de caso. Los créditos obtenidos quedan registrados y pueden ser auditados por los organismos reguladores.',
      logo: LOGOS.CPESponsors,
    },
    Busuu: {
      about: 'Busuu es una plataforma en línea similar a Duolingo para el aprendizaje de idiomas, disponible como aplicación web y móvil, que ofrece cursos interactivos para aprender y practicar 14 idiomas. Combina autoaprendizaje con un sistema de comunidad donde los usuarios pueden corregir ejercicios de otros y recibir correcciones, además de ofrecer la opción de lecciones en directo con profesores y certificados reconocidos por su contenido. \n\nPara obtener un certificado oficial, los estudiantes deben completar todos los niveles de un curso de idioma y aprobar las pruebas finales. Los certificados son emitidos en colaboración con organizaciones educativas asociadas, y reflejan el nivel alcanzado según el Marco Común Europeo de Referencia (MCER).',
      logo: LOGOS.Busuu,
    },
    UTN: {
      about: 'La Universidad Tecnológica Nacional (UTN) es una universidad pública y gratuita de Argentina, dedicada a la formación de ingenieros y profesionales en tecnología, con una red de facultades regionales en todo el país. Fundada en 1948 como la Universidad Obrera Nacional, tiene un enfoque en la educación pública, la investigación aplicada al desarrollo industrial y nacional, y la inclusión social, con carreras gratuitas y un fuerte vínculo con el sector productivo. \n\nPara aprobar los cursos y diplomaturas, los estudiantes deben asistir a clases teóricas y prácticas, rendir parciales y finales, y en algunos casos presentar proyectos o trabajos integradores. Los certificados emitidos por la UTN gozan de reconocimiento oficial en toda Argentina.',
      logo: LOGOS.UTN,
    },
    Santex: {
      about: 'Santex es una compañía tecnológica que organiza y respalda XAcademy, un programa de formación gratuita y virtual que busca cerrar la brecha entre las habilidades demandadas en el sector IT y el acceso a esa formación, fomentando la inserción laboral en áreas como programación y testing de software. \n\nLos estudiantes que participan en XAcademy deben completar módulos prácticos con proyectos guiados, y presentar entregables que son evaluados por mentores de la empresa. Una vez aprobados los proyectos y evaluaciones, reciben un certificado avalado por Santex, que valida las competencias adquiridas y puede ser utilizado en procesos de selección laboral.',
      logo: LOGOS.santex,
    },
    EPAM: {
        about: 'EPAM es una empresa estadounidense de servicios de ingeniería digital y transformación, que ofrece soluciones de desarrollo de productos de software, plataformas digitales, nube e inteligencia artificial para empresas globales y startups.',
        logo: LOGOS.EPAM,
    },
  },
    greeting: '¡Bienvenido a mi portfolio!',
    about: 'Mi nombre es Jairo Leonardo Olivera Sawka, soy desarrollador fullstack ubicado en América latina con experiencia como desarrollador semi-senior en una compaía multinacional ubicada en London, Inglaterra, Reino Unido. Tengo más de 7 años de experiencia diseñando aplicaciones web escalables con Python, Django, JavaScript (React, Node.js) y bases de datos SQL. A lo largo de mi carrera he estado implicado en todo el ciclo de vida de los productos pasando por la arquitectura backend, integraciones de APIs, creación de interfaces frontend y despliegues en contenedores con Docker. También he colaborado en soporte técnico, resolución de bugs en producción y guiado a equipos de forma técnica y proactiva. Recientemente he ampliado mi perfil hacia la inteligencia artificial desarrollando proyectos como un chatbot basado en modelos LLM o un sistema de detección de personas en imagen en tiempo real con YOLOv8. Me entusiasma encontrar soluciones eficientes, comunicarme claramente y aprender cada día con cada nuevo reto. Estaré encantado de unirme a su equipo y aportar mi experiencia, versatilidad y enfoque resultado.',
    skills: 'Tecnologías que utilizo:',
    stack: {
      labels: ['Lenguajes y estándares', 'Frontend', 'Backend', 'Bases de datos', 'DevOps', 'Testing', 'Inteligencia artificial', 'Herramientas', 'Habilidades blandas', 'Idiomas'],
      languages: ['JavaScript', 'Typescript', 'Python', 'Java', 'SQL', 'C#', 'Bash', 'HTML', 'CSS'],
      frontend: ['React', 'Redux', 'Next', 'TailwindCSS', 'MaterialUI', 'Bootstrap', 'Responsive design', 'Accessibility', 'UX writing'],
      backend: ['NodeJs', 'Express', 'FastAPI', 'Django', 'GraphQL', 'RESTful API design', 'OAuth2', 'Token authentication', 'Access Control', 'Microservices', 'MVC', 'JSON', 'Postman'],
      databases: ['MySQL', 'PostgreSQL', 'MongoDB', 'SQLite'],
      devops: ['Docker', 'CI/CD', 'Git', 'Github', 'Azure', 'HTTPS'],
      testing: ['Jest', 'Cypress', 'Pytest', 'Unit testing', 'QA automation'],
      ai: ['OpenAI', 'Groq', 'LLM integration', 'n8n', 'YOLOv8', 'Pandas', 'Data visualization', 'Basic AI modeling'],
      tools: ["Wordpress", "Wix", "Duda", 'Odoo', 'Magento', 'Prestashop', 'Figma', 'Miro', 'Powerpoint', 'Google Sheets', 'Excel', 'Word', 'Airtable'],
      softskills: ['Teamwork', 'Troubleshooting', 'Critical thinking', 'Technical documentation', 'Project management', 'INTJ'],
      languagesSpoken: ['English', 'Italian', 'Japanese', 'Polish'],
    },
    workExperienceTitle: 'Experiencia laboral',
    workLabels: {from:'Desde', to:'Hasta', position:'Puesto/Rol', company:'Empresa', highlights:'Responsabilidades y logros', technologies:'Tecnologías'},
    workExperience: [
      {iconImage: LOGOS.PWC, from: "Oct 2022", to: "Dic 2024", jobtitle: "Asociado 2", company: "PricewaterhouseCoopers", highlights: [ "Entregué mejoras de alta calidad para una aplicación web en React-TypeScript para Bristol-Myers Squibb, asegurando el alineamiento del proyecto y la satisfacción del cliente.", "Lideré la migración de una base de datos de SharePoint a una plataforma escalable, mejorando la eficiencia y usabilidad.", "Mantuve una sólida plataforma de soporte basada en Azure para NBCUniversal, garantizando una operación fluida y resolución de incidencias." ], tecnologies: [ "Trello", "Miro", "Figma", "JavaScript", ".NET", "C#", "Sharepoint", "React", "Redux", "Typescript", "MySQL", 'JSON', 'Postman' ]},
      {iconImage: LOGOS.Oliteam, from: "Ene 2020", to: "Oct 2022", jobtitle: "Gerente de Proyecto", company: "OliTeam", highlights: [ "Cofundé la organización, supervisando proyectos de pequeña escala y mentoreando a nuevos desarrolladores.", "Introduje rutas innovadoras de programación para acelerar el desarrollo de habilidades entre miembros junior del equipo." ], tecnologies: [ "Java", "Python", "JavaScript", "NodeJs", "Express", "React", "Redux", "Wordpress", "Wix", "Duda", "MongoDB", "PostgreSQL", "MySQL", "PL/SQL", 'JSON', 'Postman' ]},
      {iconImage: LOGOS.Halala, from: "Ene 2020", to: "Feb 2021", jobtitle: "Desarrollador Frontend", company: "Halalá", highlights: [ "Diseñé y desarrollé una aplicación de comercio electrónico mobile-first que conectaba productores de materia prima con fabricantes.", "Encabecé el proceso de diseño UI/UX, mejorando el compromiso del usuario y la eficiencia de navegación." ], tecnologies: [ "JavaScript", "React", "Redux", "PostgreSQL"]},
      {iconImage: LOGOS.Tecnicina, from: "Oct 2013", to: "Dic 2017", jobtitle: "Administrador de Base de Datos", company: "Tecnicina", highlights: [ "Aseguré la precisión y funcionalidad de una base de datos comercial para ventas de equipamiento médico.", "Resolví problemas operativos relacionados con la impresión de facturas y la registración fiscal, mejorando la confiabilidad del flujo de trabajo." ], tecnologies: [ "Factusol", "Magento", "Odoo", 'Prestashop', "Python", "JavaScript", 'JSON', 'Postman']}
    ],
    projectsTitle: 'Proyectos',
    projects: [
      {
        title: 'Nuntius',
        description: 'Aplicación CRUD de noticias con React, TypeScript, Node.js y PostgreSQL.',
        image: '/projects/nuntius/Nuntius_test.png',
        link: 'https://github.com/leosawka/nuntius',
      },
      {
        title: 'ToDo List',
        description: 'Gestor de tareas simple construido con React y alojado en GitHub Pages.',
        image: '/projects/todolist/ToDoList.png',
        link: 'https://leosawka.github.io/ToDo/',
      },
      {
        title: 'Trabajo en proceso',
        description: 'Completaré esta información a la brevedad.',
        image: '/projects/work in progress.png',
        link: 'https://github.com/leosawka',
      },
      {
        title: 'Trabajo en proceso #1',
        description: 'Completaré esta información a la brevedad.',
        image: '/projects/work in progress.png',
        link: 'https://github.com/leosawka',
      },
      {
        title: 'Trabajo en proceso #2',
        description: 'Completaré esta información a la brevedad.',
        image: '/projects/work in progress.png',
        link: 'https://github.com/leosawka',
      },
      {
        title: 'Trabajo en proceso #3',
        description: 'Completaré esta información a la brevedad.',
        image: '/projects/work in progress.png',
        link: 'https://github.com/leosawka',
      },
      {
        title: 'Trabajo en proceso #4',
        description: 'Completaré esta información a la brevedad.',
        image: '/projects/work in progress.png',
        link: 'https://github.com/leosawka',
      },
      {
        title: 'Trabajo en proceso #5',
        description: 'Completaré esta información a la brevedad.',
        image: '/projects/work in progress.png',
        link: 'https://leosawka.github.io/ToDo/',
      },
    ],
    socialTitle: 'Redes y contacto',
    social: [
      { label: 'Github', url: 'https://github.com/leosawka'},
      { label: 'Linkedin', url: 'https://www.linkedin.com/in/jairo-leonardo-olivera-sawka-623732b4/'},
      { label: 'Gmail', url: 'leonardo.sawka@gmail.com'},
      { label: 'Telegram', url: 'https://t.me/leonardosawka'},
      { label: 'Platzi', url: 'https://platzi.com/p/Sawka/'},
      { label: 'HackerRank', url: 'https://www.hackerrank.com/profile/Sawka'}
    ],
    coursesTitle: 'Cursos realizados',
    coursesLabels: {date: 'Fecha', ID:'Código del certificado'},
    viewMore: 'Ver más ▼',
    viewLess: 'Ver menos ▲',
    courses: [
      {
          title: 'DevOps Fundamentals',
          description: 'Este curso representa la tercera etapa de un programa de aprendizaje DevOps de cuatro cursos, que abarca conceptos clave como CI/CD, Jenkins, Docker, fundamentos de la automatización y prácticas modernas de entrega de software.',
          date: 'Octover 25, 2025',
          certificateId: 'AAAAB1KI',
          logo: LOGOS.EPAM,
          provider: 'EPAM',
      },
      {
        title: 'Automatización QA',
        description: 'Programa intensivo de XAcademy que enseña testing manual y, al completarlo, permite avanzar a pruebas automatizadas con Cypress y APIs en modalidad online.',
        date: 'August 7, 2025',
        certificateId: 'No tiene',
        logo: LOGOS.santex,
        provider: 'Santex',
      },
      {
        title: 'Introducción al aprendizaje automático',
        description: 'Introduce conceptos fundamentales de machine learning como aprendizaje supervisado y no supervisado, evaluación de modelos e ingeniería de características.',
        date: 'April 11, 2025',
        certificateId: '5f6f09dO-4cdd-4668-9cec-554528bf29be',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Los secretos de la comunicación interpersonal',
        description: 'Explora técnicas para desarrollar empatía, escucha activa y habilidades de resolución de conflictos esenciales para una comunicación interpersonal efectiva.',
        date: 'April 07, 2025',
        certificateId: 'e7bd75a0c6116c65111c5860b00301f6c58fa2da9844fa1b70e80376cf2a2f2c',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Fundamentos de la gestión de proyectos: proyectos pequeños',
        description: 'Cubre metodologías clave de gestión de proyectos y las fases de planificación, ejecución y cierre adaptadas a proyectos de pequeña escala.',
        date: 'March 29, 2025',
        certificateId: '889ed3a0a890f280e2a17d9b54acbe09ebee12afb5cc0b6f2da903f680421c2b',
        logo: LOGOS.projectManagementInstitude,
        provider: 'Project Management Institute'
      },
      {
        title: 'Estructuras de datos en Python: pilas, colas dobles y colas',
        description: 'Explica cómo implementar y utilizar pilas, deques y colas en Python con ejemplos prácticos y consideraciones de rendimiento.',
        date: 'March 19, 2025',
        certificateId: '20ae047f9fa7d58bab398e25fb8818281556f7454298221763269d38fd05467a',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Gestión de proyectos simplificada',
        description: 'Ofrece un enfoque simplificado a las técnicas de gestión de proyectos, centrándose en la eficiencia y aplicación práctica en entornos dinámicos.',
        date: 'March 19, 2025',
        certificateId: '096a973c00084b688a3c2ae5dee929be82afb2f52e15323b76bddea703ead7b6',
        logo: LOGOS.projectManagementInstitude,
        provider: 'Project Management Institute',
      },
      {
        title: 'Estructuras de datos en Python: listas enlazadas',
        description: 'Enseña la creación, recorrido y manipulación de listas enlazadas en Python, con énfasis en el rendimiento.',
        date: 'March 18, 2025',
        certificateId: 'fc699f25238fc3b35c3bf63edf081c708e326c83dbad83a6fd0236c302251241',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Estructuras de datos y algoritmos en Python',
        description: 'Introduce estructuras de datos esenciales y patrones de diseño de algoritmos en Python, incluyendo recursividad y técnicas de ordenamiento.',
        date: 'March 17, 2025',
        certificateId: '759900d11cb37f50e7b486988192a48bdd1af6f85187eb14bfc25a0d8110436c',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Python avanzado: ejemplos prácticos con bases de datos',
        description: 'Demuestra la interacción con bases de datos en Python mediante ejemplos reales con bases SQL y ORMs.',
        date: 'March 07, 2025',
        certificateId: '83d11b8a007541ee3dc1b1e544e057565206595a78e6b02bbe8ca39328c838d7',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Python avanzado: trabajando con bases de datos',
        description: 'Explora técnicas avanzadas para consultas, manejo de transacciones y optimización de operaciones en bases de datos con Python.',
        date: 'February 26, 2025',
        certificateId: '20b01b7dedb39a9a4472ada6eea77ae75589f7678b242247c367283934386297',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Teletrabajo y gestión de equipos remotos',
        description: 'Cubre buenas prácticas, herramientas y estrategias de liderazgo para gestionar equipos distribuidos y remotos de forma efectiva.',
        date: 'February 21, 2025',
        certificateId: 'a277f3adf2c306aa37e589a6e319827917d4738ae0c4a04aa0ca8824056601d6',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Python avanzado: trabajando con datos',
        description: 'Se centra en técnicas de manipulación y procesamiento de datos en Python, incluyendo el manejo de JSON, CSV y grandes volúmenes de datos.',
        date: 'February 20, 2025',
        certificateId: '0562865fff9a168ddca24ca66d3928e1bdcba69ac02e4420988acbf7a737c93b',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Estadística esencial con Python',
        description: 'Introduce conceptos estadísticos básicos y su implementación en Python, incluyendo estadística descriptiva y visualización de datos.',
        date: 'February 17, 2025',
        certificateId: '4659c82fbc20cc5644c9bdb663b284562b4b808c57bafc22a7e724223bd9da34',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Estadística esencial con Python (CPE)',
        description: 'El mismo contenido que el curso esencial, pero con créditos de Educación Profesional Continua (CPE).',
        date: 'February 17, 2025',
        certificateId: 'b497d69a8de2f88252ffad414fe63b10cde5ebd2b489eb0b1ff10ca3478bedf6',
        logo: LOGOS.CPESponsors,
        provider: 'CPE Sponsors',
      },
      {
        title: 'Matemática fundamental para aprendizaje automático',
        description: 'Cubre fundamentos matemáticos esenciales para machine learning, incluyendo álgebra lineal, cálculo y teoría de probabilidades.',
        date: 'February 06, 2025',
        certificateId: 'e6c77c5aaeeafade3d656ed4ae790d8ec215f47d7df392e1d91d8fa41d9756a5',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Fundamentos de ML: estadística (CPE)',
        description: 'Presenta conceptos estadísticos esenciales para comprender machine learning, diseñado para créditos CPE.',
        date: 'February 07, 2025',
        certificateId: '21014f9053fb006f8cb6a71bff3e5ef4f8b66227faaa005d99de63a24519d63c',
        logo: LOGOS.CPESponsors,
        provider: 'CPE Sponsors',
      },
      {
        title: 'Fundamentos de ML: estadística (LinkedIn)',
        description: 'Introduce fundamentos de estadística relevantes para ML, con foco en varianza, correlación e inferencia.',
        date: 'February 06, 2025',
        certificateId: '13c1115f65b43a09726f15c3d2739748e4bae3a0c372a842200b85344c499554',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Fundamentos de ML: probabilidad',
        description: 'Cubre teoría de probabilidades esencial para ML, incluyendo teorema de Bayes, distribuciones y métodos de muestreo.',
        date: 'February 05, 2025',
        certificateId: 'da1e89b23e30220ef96bca44c8b628bd99dbe7fb97338f5967acedd8bd9127ac',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Fundamentos de ML: cálculo',
        description: 'Explora temas de cálculo como derivadas e integrales y sus aplicaciones en optimización para ML.',
        date: 'February 03, 2025',
        certificateId: '5231f5fc974667ecb9f1f31155ea5f5b4924a93cdbb983ac1f51b418b6ae9167',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Fundamentos de ML: álgebra lineal',
        description: 'Introduce vectores, matrices y operaciones relevantes para algoritmos de machine learning.',
        date: 'January 29, 2025',
        certificateId: '475599a829ce4c9544175528878e2df05ae33a4125a3bfb397248feee1c3f809',
        logo: LOGOS.linkedin,
        provider: 'LinkedIn Learning',
      },
      {
        title: 'Gestión de trabajo con Airtable',
        description: 'Enseña cómo organizar, hacer seguimiento y automatizar flujos de trabajo en Airtable para una gestión eficiente de proyectos y tareas.',
        date: 'January 22, 2025',
        certificateId: '49e8a987-08ff-489e-a8cb-0388fa280ee4',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Introducción a la terminal y línea de comandos',
        description: 'Introducción práctica a la línea de comandos, cubriendo navegación, operaciones con archivos y herramientas esenciales del terminal.',
        date: 'October 21, 2024',
        certificateId: 'Oa320131-0b60-463d-aa74-eaa392c3db06',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Inglés intermedio-alto B2',
        description: 'Curso diseñado para consolidar habilidades de escucha, conversación, lectura y escritura en nivel B2.',
        date: 'October 14, 2024',
        certificateId: '5196524b-3dfa-4a11-a53a-b3f93f55e954',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Fundamentos de diseño de interfaces UX/UI',
        description: 'Introducción a los principios de UX/UI, con enfoque en diseño de experiencias y prototipado de interfaces.',
        date: 'July 14, 2024',
        certificateId: '190fbdc9-d6df-4fc1-a880-f58803c9a85c',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Guía para aprender seguridad informática',
        description: 'Guía introductoria a conceptos clave de ciberseguridad y buenas prácticas para proteger sistemas.',
        date: 'June 06, 2024',
        certificateId: '90c6e780-1949-4dd2-aeec-af3e47f84890',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'React.Js',
        description: 'Cubre los fundamentos de React.js, incluyendo componentes, estado y routing para desarrollo frontend moderno.',
        date: 'March 13, 2024',
        certificateId: '5fe5fad7-1a9c-4f9b-976d-134c14906137',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Fundamentos de C# con .NET Core',
        description: 'Introduce conceptos fundamentales de programación en C# y desarrollo con .NET Core.',
        date: 'December 04, 2022',
        certificateId: 'e5445efO-2e90-482b-9575-7c7710e9c7f3',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Fundamentos de .NET',
        description: 'Introducción al ecosistema .NET, cubriendo su arquitectura y herramientas principales.',
        date: 'December 04, 2022',
        certificateId: '5b54f314-5002-4e68-b1aa-01e267a104c6',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Curso profesional de Scrum',
        description: 'Formación profesional en Scrum que cubre roles, eventos y artefactos en entornos ágiles.',
        date: 'November 14, 2022',
        certificateId: '3ec96a11-e093-4436-96fe-950cf07621eс',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Programación orientada a objetos',
        description: 'Cubre principios de POO como clases, herencia y encapsulación.',
        date: 'November 07, 2022',
        certificateId: 'e1b18ed5-9256-4f5d-9d24-06670b6b3c2a',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Git y GitHub',
        description: 'Introducción a Git y GitHub: control de versiones, repositorios, ramas y pull requests.',
        date: 'November 07, 2022',
        certificateId: '542a3d3d-a506-4200-9a90-c648d710c067',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Programación básica',
        description: 'Curso inicial de programación que cubre lógica, estructuras de datos básicas y sintaxis fundamental.',
        date: 'November 04, 2022',
        certificateId: 'e09b242f-4491-470a-85bd-8163ca3becaa',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Nivel A1 de japonés',
        description: 'Curso de japonés nivel A1 enfocado en vocabulario, gramática básica y expresiones cotidianas.',
        date: 'September 21, 2022',
        certificateId: 'No tiene.',
        logo: LOGOS.Busuu,
        provider: 'Busuu',
      },
      {
        title: 'Introducción a C#',
        description: 'Curso introductorio a C# que cubre sintaxis básica, tipos de datos y estructuras de control.',
        date: 'February 04, 2022',
        certificateId: 'd1231e44-a9f0-4833-bd98-a3bc2e2f27ba',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Fundamentos de Node.Js',
        description: 'Principios esenciales de Node.js para construir aplicaciones del lado del servidor con JavaScript.',
        date: 'Octover 25, 2021',
        certificateId: '1775267f-9299-4a2a-9d03-6ab46a369f15',
        logo: LOGOS.platzi,
        provider: 'Platzi',
      },
      {
        title: 'Liquidación de sueldos',
        description: 'Brinda formación teórica y práctica para calcular sueldos, salarios, aportes a la seguridad social y deducciones de acuerdo con la normativa laboral Argentina.',
        date: 'December 10, 2018',
        certificateId: 'No tiene.',
        logo: LOGOS.UTN,
        provider: 'UTN',
      },
    ],
    contactTitle: 'Contáctame',
    "contactForm": {
      "name": "Nombre",
      "email": "Correo electrónico",
      "message": "Mensaje",
      "send": "Enviar",
      "success": "¡Mensaje enviado!",
      "error": "Por favor completá todos los campos.",
      "invalidFormat": "Formato de correo inválido.",
      "disposableEmail": "No se permiten correos temporales o bloqueados.",
      "errorName": "El nombre es obligatorio.",
      "errorEmail": "El correo es obligatorio.",
      "errorMessage": "El mensaje es obligatorio."
    }
} as const;
